import { readFile, writeFile, readdir, mkdir, copyFile, cp } from 'node:fs/promises';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const manifest = JSON.parse(await readFile(resolve(root, 'manifest.json'), 'utf8'));
const styles = (await readdir(resolve(root, 'src'))).filter(f => f.endsWith('.css')).sort();
const fonts = [
  ['regular', 'normal', 400], ['italic', 'italic', 400],
  ['bold', 'normal', 700], ['bolditalic', 'italic', 700],
];
let css = `/* Quiet Paper ${manifest.version} | MIT (theme) | TeX Gyre fonts: GUST Font License.\n * Generated by npm run build; edit src/*.css instead.\n */\n\n`;
for (const [face, style, weight] of fonts) {
  const data = await readFile(resolve(root, `assets/fonts/texgyrepagella-${face}.woff2`));
  css += `@font-face {\n  font-family: "Quiet Pagella";\n  font-style: ${style};\n  font-weight: ${weight};\n  font-display: swap;\n  src: url("data:font/woff2;base64,${data.toString('base64')}") format("woff2");\n}\n\n`;
}
for (const file of styles) css += `/* ${file} */\n${(await readFile(resolve(root, 'src', file), 'utf8')).replace(/\r\n/g, '\n')}\n`;
await writeFile(resolve(root, 'theme.css'), css);
for (const directory of ['dist/Quiet Paper', 'demo-vault/.obsidian/themes/Quiet Paper']) {
  const target = resolve(root, directory);
  await mkdir(target, { recursive: true });
  for (const file of ['theme.css', 'manifest.json']) await copyFile(resolve(root, file), resolve(target, file));
}
const dist = resolve(root, 'dist/Quiet Paper');
await mkdir(resolve(dist, 'licenses'), { recursive: true });
for (const file of ['README.md', 'LICENSE', 'ATTRIBUTION.md', 'CHANGELOG.md', 'CONTRIBUTING.md']) {
  await copyFile(resolve(root, file), resolve(dist, file));
}
await cp(resolve(root, 'docs'), resolve(dist, 'docs'), { recursive: true });
for (const file of ['GUST-FONT-LICENSE.txt', 'LPPL-1.3c.txt']) {
  await copyFile(resolve(root, 'assets/fonts', file), resolve(dist, 'licenses', file));
}
await copyFile(resolve(root, 'assets/fonts/README.md'), resolve(dist, 'licenses/FONT-NOTICE.md'));
console.log(`Built ${manifest.name} ${manifest.version}: ${Math.round(Buffer.byteLength(css) / 1024)} KiB, ${styles.length} CSS modules, 4 embedded font faces.`);
